#![allow(non_camel_case_types, clippy::identity_op)]
/** Minimal xkb_common ffi wrapper, loosely based on sctk's. */

use std::os::raw::c_char;

#[repr(C)] pub struct xkb_context {_private: [u8; 0]}
#[repr(C)] pub struct xkb_keymap {_private: [u8; 0]}
#[repr(C)] pub struct xkb_state {_private: [u8; 0]}

pub type xkb_keycode_t = u32;
pub type xkb_keysym_t = u32;
pub type xkb_layout_index_t = u32;
pub type xkb_mod_mask_t = u32;

#[repr(C)]
#[derive(Copy, Clone, Debug, PartialEq)]
pub enum xkb_context_flags {
    /** Do not apply any context flags. */
    XKB_CONTEXT_NO_FLAGS = 0,
}

#[repr(C)]
#[derive(Copy, Clone, Debug, PartialEq)]
pub enum xkb_keymap_compile_flags {
    /** Do not apply any flags. */
    XKB_KEYMAP_COMPILE_NO_FLAGS = 0,
}

#[repr(C)]
#[derive(Copy, Clone, Debug, PartialEq)]
pub enum xkb_keymap_format {
    /** The current/classic XKB text format, as generated by xkbcomp -xkb. */
    XKB_KEYMAP_FORMAT_TEXT_V1 = 1,
}

pub type xkb_state_component = u32;

#[link(name = "xkbcommon")]
extern "C" {
    pub fn xkb_keysym_to_utf32(_: xkb_keysym_t) -> u32;
    pub fn xkb_context_new(_: xkb_context_flags) -> *mut xkb_context;
    pub fn xkb_context_unref(_: *mut xkb_context) -> ();
    pub fn xkb_keymap_new_from_string(_: *mut xkb_context,
                                  _: *const c_char,
                                  _: xkb_keymap_format,
                                  _: xkb_keymap_compile_flags
                                 ) -> *mut xkb_keymap;
    pub fn xkb_keymap_unref(_: *mut xkb_keymap) -> ();
    pub fn xkb_state_key_get_one_sym(_: *mut xkb_state, _: xkb_keycode_t) -> xkb_keysym_t;
    pub fn xkb_state_new(_: *mut xkb_keymap) -> *mut xkb_state;
    pub fn xkb_state_unref(_: *mut xkb_state) -> ();
    pub fn xkb_state_update_mask(_: *mut xkb_state,
                             _: xkb_mod_mask_t,
                             _: xkb_mod_mask_t,
                             _: xkb_mod_mask_t,
                             _: xkb_layout_index_t,
                             _: xkb_layout_index_t,
                             _: xkb_layout_index_t
                            ) -> xkb_state_component;
}
